export const commonExpenses = [
    "Wharfage & Handling",
    "CFC Charges & transportation(VAT exclusive)",
    "Freight charges",
    "Detention fee",
    "Treatment and inspection fee",
    "Phytosanitary & processing fee",
    "TFS charge(Export permit) & processing",
    "Fimigation charge",
    "Certificate of origin",
    "Tripping/stuffing charges & weight charge",
    "Storage charges",
    "Tax payment",
    "TBS charges",
    "Transport from TPA to MSC",
    "Penalt notice fee",
    "ICD Handling charges",
    "TPA wharfage",
    "Transfer charges",
    "Ocean freight",
    "Unloading",
    "Manifest",
    "BL fee",
    "TRA Amendment",
    "Position of empty container",
    "Purchase of new containers",
    "Port charges",
    "Airfreight charge",
    "Cargo declaration",
    "Air waybill fee",
    "Swissport handling",
    "Cargo pick up",
    "Packing & wrapping",
    "VAT 18%",
    "Local charges",
    "Shipping line storage",
    "Atomic fee",
    "Mps cancelation fee",
    "Courier charges",
    "Annex stamp for TRA",
    "Demmurage charges",
    "Liner bags and bulking fee",
    "ICO",
    "GCLA",
    "Rent",
    "Facilitation to GCLA",
    "Amendment for booking no",
    "TASAC fee",
    "Boarder clearance",
    "D/O fee",
    "Motor vehicle insurance",
    "Card and plate number",
    "Quality certificate",
    "Jumbo bags and pallets",
    "Weighing charge(VGM)",
    "Transport and all other charges at Dar port",
    "Offloading & Weighing",
    "Stuffing & Weighing",
    "Bulk Bag",
    "Rope",
    "Tansfer Of Full Container",
    "Transport TOo The Working Area",
    "Facilitation To Accomplish The Task",
    "Payment for C.O.O",
    "Phytsanitary Certificate",
    "Fuel Fee In Motorcycle",
    "Maintanance & Services",
]