<template>
    <div class="flex flex-wrap sm:flex-row gap-8">
      <div class="w-full rounded-2xl bg-white p-4 shadow-lg">
        <div class="m-auto block">
              <table class="w-full divide-y divide-gray-200">
                <thead class="bg-gray-100">
                  <tr class="">
                    <th class="px-4 py-2 text-left">Consignment</th>
                    <th class="px-4 py-2 text-left">Generated By</th>
                    <th class="px-4 py-2 text-left">Doc Type</th>
                    <th class="px-4 py-2 text-left">Date Created</th>
                    <th class="px-4 py-2 text-left">Actions</th>
                  </tr>
                </thead>
                <tbody>
                  <InvoiceStatementEntry 
                    v-for="item in taxInvoices" 
                    :item="item" 
                    :key="item.ID"
                    @delete-clicked="loadDeleteStatementDialog(item.ID)"
                    @preview-invoice="loadTaxInvoicePreview"
                    @preview-debit-note="loadDebitNotePreview"
                    />
                </tbody>
              </table>
        </div>
      </div>
      <DeleteDialog 
        v-if="showDeleteStatementDialog" 
        entity="Statement" 
        :loading="deleteInProgress" 
        @proceed="deleteStatement" 
        @close="closeDeleteDialog"/>

        <TaxInvoicePreview v-if="showTaxInvcPreview" :doc="taxInvoiceToPreview" :entries="taxInvoiceToPreview.particulars" @close="taxInvoicePreviewClosed"/>
    </div>
  </template>
  
  <script setup>
  import { ref, onMounted } from 'vue';


  // definePageMeta({
  //   middleware: 'permissions',
  //   permissions: ['can-read-invoices']
  // });

  const { $axios } = useNuxtApp()
  
  const taxInvoices = ref([]);
  const debitNotes = ref([]);
  const invoicesActive = ref(true)
  
  const currentDate = new Date();
  
  
  //CRUD SHIT
  const showCreateStatementForm = ref(false)
  const showTaxInvcPreview = ref(false)
  const showDeleteStatementDialog = ref(false)
  const taxInvoiceToPreview = ref({});
  const debitNoteToPreview = ref({});
  const statementToDelete = ref(0);
  const deleteInProgress = ref(false)

  function taxInvoicePreviewClosed(invoice){
    showTaxInvcPreview.value = false
  }

  function loadTaxInvoicePreview(id){
    if(id){
      taxInvoiceToPreview.value = taxInvoices.value.find(item => item.ID === id)?.taxInvoice
    }
    showTaxInvcPreview.value = true
  }

  function loadDebitNotePreview(id){
    debitNoteToPreview.value = debitNotes.value.find(item => item.ID === id)
  }

  async function getStatements(){
    try {
      const response = await $axios.get('/api/statements');
      taxInvoices.value = response.data;
    } catch (error) {
      console.error('Error fetching data:', error);
      taxInvoices.value = null; // Set items to an empty array or handle error as needed
    }
  }

  async function getDebitNotes(){
    try {
      const response = await $axios.get('/api/debit-note');
      debitNotes.value = response.data;
    } catch (error) {
      console.error('Error fetching data:', error);
      debitNotes.value = null; // Set items to an empty array or handle error as needed
    }
  }

  async function downloadStatementClicked(doc){
    if (doc) {
      try {
        const res = await $axios.get(`/api/statements/download/${doc.filename}`, { responseType: 'blob' });
        const url = window.URL.createObjectURL(new Blob([res.data]));
        const link = document.createElement('a');
        link.href = url;
        link.setAttribute('download', doc.filename); // or set a different filename if needed
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        window.URL.revokeObjectURL(url);
      } catch (error) {
        console.error('Error downloading the file:', error);
        alert('Error downloading the file. Please try again.');
      }
    }
  }

  function convertDateFormat(dateString) {
  // Create a new Date object from the input string
  const inputDate = new Date(dateString);

  // Format the date as "DDD/MM/YY"
  const year = inputDate.getFullYear();
  const month = String(inputDate.getMonth() + 1).padStart(2, '0');
  const day = String(inputDate.getDate()).padStart(2, '0');
  const formattedDate = `${day}/${month}/${year}`;

  return formattedDate;
}

  
  
  function loadDeleteStatementDialog(id){
    statementToDelete.value = id;
    showDeleteStatementDialog.value = true
  }
  
  function closeDeleteDialog(){
    deleteInProgress.value = false;
    showDeleteStatementDialog.value=false;
  }
  async function deleteStatement(id){
    deleteInProgress.value = true
    const res = await $axios.delete(`/api/statements/delete/${statementToDelete.value}`);
    console.log(res)
    if(res.status==200 || 201){
        await getStatements()
        showDeleteStatementDialog.value = false;
    }else{
        console.log(res.statusText)
    }
  }

  async function deleteDebitNote(){
    deleteInProgress.value = true
    const res = await $axios.delete(`/api/debit-note/${debitNoteToDelete.value}`);
    console.log(res)
    if(res.status==200 || 201){
        await getDebitNotes()
        showDeleteDebitNoteDialog.value = false;
    }else{
        console.log(res.statusText)
    }
  }
  
  
  onMounted(async () => {
    await getStatements()
    await getDebitNotes()
  });
  
  </script>